/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CoturnSetupRouteImport } from './routes/coturn-setup'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as CallsIndexRouteImport } from './routes/calls.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as MessagesPeerIdRouteImport } from './routes/messages.$peerId'
import { Route as CallsCallIdRouteImport } from './routes/calls.$callId'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CoturnSetupRoute = CoturnSetupRouteImport.update({
  id: '/coturn-setup',
  path: '/coturn-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesPeerIdRoute = MessagesPeerIdRouteImport.update({
  id: '/messages/$peerId',
  path: '/messages/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsCallIdRoute = CallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/coturn-setup': typeof CoturnSetupRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/visitors': typeof VisitorsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/calls/': typeof CallsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/coturn-setup': typeof CoturnSetupRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/visitors': typeof VisitorsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/calls': typeof CallsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/coturn-setup': typeof CoturnSetupRoute
  '/friends': typeof FriendsRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/visitors': typeof VisitorsRoute
  '/calls/$callId': typeof CallsCallIdRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/calls/': typeof CallsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/coturn-setup'
    | '/friends'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/premium'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/safety'
    | '/shop'
    | '/support'
    | '/visitors'
    | '/calls/$callId'
    | '/messages/$peerId'
    | '/rooms/$slug'
    | '/u/$userId'
    | '/calls/'
    | '/messages/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/coturn-setup'
    | '/friends'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/premium'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/safety'
    | '/shop'
    | '/support'
    | '/visitors'
    | '/calls/$callId'
    | '/messages/$peerId'
    | '/rooms/$slug'
    | '/u/$userId'
    | '/calls'
    | '/messages'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/coturn-setup'
    | '/friends'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/premium'
    | '/pricing'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/safety'
    | '/shop'
    | '/support'
    | '/visitors'
    | '/calls/$callId'
    | '/messages/$peerId'
    | '/rooms/$slug'
    | '/u/$userId'
    | '/calls/'
    | '/messages/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  CoturnSetupRoute: typeof CoturnSetupRoute
  FriendsRoute: typeof FriendsRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  PremiumRoute: typeof PremiumRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RewardsRoute: typeof RewardsRoute
  SafetyRoute: typeof SafetyRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  VisitorsRoute: typeof VisitorsRoute
  CallsCallIdRoute: typeof CallsCallIdRoute
  MessagesPeerIdRoute: typeof MessagesPeerIdRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  UUserIdRoute: typeof UUserIdRoute
  CallsIndexRoute: typeof CallsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coturn-setup': {
      id: '/coturn-setup'
      path: '/coturn-setup'
      fullPath: '/coturn-setup'
      preLoaderRoute: typeof CoturnSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$peerId': {
      id: '/messages/$peerId'
      path: '/messages/$peerId'
      fullPath: '/messages/$peerId'
      preLoaderRoute: typeof MessagesPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$callId': {
      id: '/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/calls/$callId'
      preLoaderRoute: typeof CallsCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  CoturnSetupRoute: CoturnSetupRoute,
  FriendsRoute: FriendsRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  PremiumRoute: PremiumRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RewardsRoute: RewardsRoute,
  SafetyRoute: SafetyRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  VisitorsRoute: VisitorsRoute,
  CallsCallIdRoute: CallsCallIdRoute,
  MessagesPeerIdRoute: MessagesPeerIdRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  UUserIdRoute: UUserIdRoute,
  CallsIndexRoute: CallsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
